#api-server:
#  service:
#    type: ClusterIP
#    port: 9000
#  image:
#    tag: "0.2.0-wip"

#frontend:
#  service:
#    type: NodePort
#    port: 80
#  image:
#    tag: "0.1.0-wip"

#device-server:
#  service:
#    type: ClusterIP
#    port: 8080
#  image:
#    tag: "0.1.0-wip"
#  env:
#    - name: MOCK_MODE
#      value: true
