services:
  reverse-proxy:
    image: nginx
    container_name: reverse-proxy_local-test
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - local-test_net
    ports:
      - "8080:80"
  frontend:
    image: ghcr.io/magurouhiru/pi-web_frontend:latest
    container_name: frontend_local-test
    networks:
      - local-test_net
    ports:
      - "8081:80"
  api-server:
    image: ghcr.io/magurouhiru/pi-web_api-server:latest
    container_name: api-server_local-test
    networks:
      - local-test_net
    ports:
      - "9090:9000"

networks:
  local-test_net:
    driver: bridge
