services:
  frontend:
    image: pi-web_frontend:latest
    container_name: frontend_local-test
    platform: linux/arm64
    networks:
      - local-test_net
    ports:
      - "8080:80"
  api-server:
    image: pi-web_api-server:latest
    container_name: api-server_local-test
    platform: linux/arm64
    networks:
      - local-test_net
    ports:
      - "9090:9000"
    depends_on:
      - db
  db:
    image: mariadb:lts
    container_name: db_local-test
    networks:
      - local-test_net
    ports:
      - "23306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: playuser
      MYSQL_PASSWORD: playpass
      MYSQL_DATABASE: playdb
    volumes:
      - db-data_local-test:/var/lib/mysql
    restart: unless-stopped

networks:
  local-test_net:
    driver: bridge

volumes:
  db-data_local-test:
