services:
  frontend:
    image: pi-web_frontend:latest
    container_name: frontend_local-test
    platform: linux/arm64
    networks:
      - local-test_net
    ports:
      - "8080:80"
  api-server:
    image: pi-web_api-server:latest
    container_name: api-server_local-test
    platform: linux/arm64
    networks:
      - local-test_net
    ports:
      - "9090:9000"
    environment:
      DB_URL: jdbc:sqlite://var/lib/sqlite3/playdb
    volumes:
      - db-data_local-test:/var/lib/sqlite3
  device-server:
    image: pi-web_device-server:latest
    container_name: device-server_local-test
    platform: linux/arm64
    networks:
      - local-test_net
    ports:
      - "8888:8080"

networks:
  local-test_net:
    driver: bridge

volumes:
  db-data_local-test:
