services:
  frontend:
    container_name: frontend_local-test
    image: pi-web_frontend:latest
    platform: linux/arm64
    networks:
      - local-test_net
    ports:
      - "8080:80"
  api-server:
    container_name: api-server_local-test
    image: pi-web_api-server:latest
    platform: linux/arm64
    networks:
      - local-test_net
    ports:
      - "9090:9000"

networks:
  local-test_net:
    driver: bridge
