services:
  frontend:
    image: node:22.15.0-bookworm
    container_name: frontend_dev
    networks:
      - devnet
    ports:
      - "14200:4200"
  api-server:
    build: ./api-server
    image: pi-web_api-server_dev:latest
    container_name: api-server_dev
    networks:
      - devnet
    ports:
      - "19000:9000"
    environment:
      APP_ENV: dev
      DB_URL: jdbc:sqlite://var/lib/sqlite3/playdb
      DEVICE_SERVER_URL: http://device-server:8080
    volumes:
      - db-data:/var/lib/sqlite3
  device-server:
    image: python:3.13.5-slim-bullseye
    container_name: device-server_dev
    networks:
      - devnet
    ports:
      - "18080:8080"
    environment:
      APP_ENV: dev
      MOCK_MODE: true

networks:
  devnet:
    driver: bridge

volumes:
  db-data:
