services:
  frontend:
    image: node:22.15.0-bookworm
    container_name: frontend_dev
    networks:
      - devnet
    ports:
      - "14200:4200"
    volumes:
      - frontend-node_modules:/frontend/node_modules
  api-server:
    build: ./api-server
    image: pi-web_api-server_dev:latest
    container_name: api-server_dev
    networks:
      - devnet
    ports:
      - "19000:9000"
    environment:
      APP_ENV: dev
      DB_URL: jdbc:sqlite://var/lib/sqlite3/playdb
      DEVICE_MOCK: true
    volumes:
      - db-data:/var/lib/sqlite3

networks:
  devnet:
    driver: bridge

volumes:
  frontend-node_modules:
  db-data:
