services:
  frontend:
    image: node:22.15.0-bookworm
    container_name: frontend_dev
    networks:
      - devnet
    ports:
      - "14200:4200"
  api-server:
    image: sbtscala/scala-sbt:eclipse-temurin-17.0.15_6_1.11.3_2.13.16
    container_name: api-server_dev
    networks:
      - devnet
    ports:
      - "19000:9000"
    depends_on:
      - db
    environment:
      DB_URL: jdbc:mysql://db:3306/playdb
      DB_USER: playuser
      DB_PASSWORD: playpass
  db:
    image: mariadb:lts
    container_name: db_dev
    networks:
      - devnet
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: playuser
      MYSQL_PASSWORD: playpass
      MYSQL_DATABASE: playdb
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped

networks:
  devnet:
    driver: bridge

volumes:
  db-data:
