services:
  frontend:
    image: node:22.15.0-bookworm
    container_name: frontend_dev
    networks:
      - devnet
    ports:
      - "4200:4200"
  api-server:
    image: sbtscala/scala-sbt:eclipse-temurin-21.0.7_6_1.11.3_2.13.16
    container_name: api-server_dev
    networks:
      - devnet
    ports:
      - "9000:9000"

networks:
  devnet:
    driver: bridge
