name: Pull Request check pi-web/api-server

on:
  pull_request:
    paths:
      - 'pi-web/api-server/**'

jobs:
  build:
    name: Build & (optionally) Push pi-web/api-server
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pi-web/api-server

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache sbt
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.coursier
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt

      - name: Run scalafmt and test
        run: |
          sbt scalafmtCheckAll compile test
