name: Build & Push pi-web/api-server

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build & (optionally) Push pi-web/api-server
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pi-web/api-server

    steps:
      - uses: actions/checkout@v4

      - name: Check for changes
        id: changes
        run: |
          BASE_REF=${{ github.event.pull_request.base.ref }}
          TARGET_BRANCH=${BASE_REF:-main}
      
          git fetch origin $TARGET_BRANCH
          
#          if git diff --name-only origin/$TARGET_BRANCH...HEAD | grep -q '^pi-web/api-server/'; then
#            echo "changed=true" >> $GITHUB_OUTPUT
#          else
#            echo "changed=false" >> $GITHUB_OUTPUT
#          fi
          echo "changed=true" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        if: steps.changes.outputs.changed == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        if: steps.changes.outputs.changed == 'true' && github.event_name == 'push'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        if: steps.changes.outputs.changed == 'true' && github.event_name == 'pull_request'
        run: make build

      - name: Push
        if: steps.changes.outputs.changed == 'true' && github.event_name == 'push'
        run: make push
