name: Push pi-web/api-server

on:
  push:
    branches:
      - main
    paths:
      - 'pi-web/api-server/**'
  pull_request:
    paths:
      - 'pi-web/api-server/**'

jobs:
  build:
    name: Build & (optionally) Push pi-web/api-server
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pi-web/api-server

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Inspect builder
        run: docker buildx inspect ${{ steps.buildx.outputs.name }} --bootstrap

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Push wip
        if: github.event_name == 'pull_request'
        run: make push_wip BUILDER=${{ steps.buildx.outputs.name }}

      - name: Push
        if: github.event_name == 'push'
        run: make push BUILDER=${{ steps.buildx.outputs.name }}
